export const GET_TAB = "GET_TAB";
export const GET_SCREEN = "GET_SCREEN";
export const GET_AUTH_TAB = "GET_AUTH_TAB";

export const SET_SOCKET="SET_SOCKET";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const ADD_CHAT_MESSAGE = "ADD_CHAT_MESSAGE";
export const LOAD_CHAT_MESSAGES = "LOAD_CHAT_MESSAGES";
export const SET_UNREAD_MESSAGES = "SET_UNREAD_MESSAGES";
export const INCREASE_RECONNECT_COUNT = "INCREASE_RECONNECT_COUNT";

export const SET_USER_DATA = "SET_USER_DATA";
export const SET_EMPLOYEES = "SET_EMPLOYEES";
export const SET_USER_FROM_LS = "SET_USER_FROM_LS";
export const UPDATE_EMPLOYEES ="UPDATE_EMPLOYEES";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const SET_COMPANY_PROFILE = "SET_COMPANY_PROFILE";


export const ADD_NEW_TENDER = 'SET_TENDERS';
export const GET_ALL_TENDERS = 'GET_ALL_TENDERS';

