import * as Localization from 'expo-localization';
import i18n from 'i18n-js';

i18n.translations = {
        uk: { 
            "personal_data": "Особисті дані",
            "contact_info": "Контактна інформація",
            "company": "Компанія",
            "surname": "По батькові",
            "name": "Ім’я",
            "last_name": "Прізвище",
            "email": "Email",
            "phone_number": "Номер телефону",
            "additional_phone_number": "Додатковий номер телефону",
            "company_name": "Назва компанії",
            "EDRPOU": "ЄДРПОУ",
            "IBAN": "IBAN номер",
            "added_max_employees": "Ви додали максимальну кількість співробітників",
            "company_contacts": "Контакти компанії",
            "docs_delivery_address": "Адреса доставки документів",
            "gods_delivery_address": "Адреса доставки товарів",
            "employees_company_list": "Список співробітників компанії",
            "full": "Повна",
            "half": "Неповна",
            "will_removed_from_employee_list": "буде видалений із списка співробітників.",
            "continue": "Продовжити?",
            "yes": "Так",
            "no": "Ні",
            "ok": "OK",
            "not_enough_rights": "На жаль у Вас недостатньо прав.",
            "of_course": "Зрозуміло",
            "employee_pib": "ПІБ співробітника",
            "employee_email": "Email співробітника",
            "employee_role": "Роль співробітника",
            "add_employee": "Додати співробітника",
            "delete_employee": "Видалити співробітника",
            "two_factor_auth": "Двофакторна автентифікація",
            "notifications": "Повідомлення",
            "FAQ": "FAQ",
            "invite_users": "Запрошення користувачів",
            "settings_language_title": "Мова додатку",
            "save_changes": "Зберегти зміни",
            "want_to_quit": "Ви впевнені, що хочете вийти?",
            "data_will_lost": "У разі незбережених даних вони будуть втрачені",
            "tech_error": "Технічна помилка!",
            "profile_changes_saved": "Дякуємо, зміни у Вашому профілі будут збережені!",
            "faq_content_title_1": "Як BuyPro проводить тендерну процедуру?",
            "faq_content_text_1": "Після Вашого погодження заказу, менеджер BuyPro супроводжує поставки до моменту закриття його, вирішуючи всі питання стосовно Якості та кількості товарів та послуг, комплектності документів та інших питань.",
            "faq_content_title_2": "Як передають  заяву на поставку?",
            "faq_content_text_2": "Після Вашого погодження заказу, менеджер BuyPro супроводжує поставки до моменту закриття його, вирішуючи всі питання стосовно Якості та кількості товарів та послуг, комплектності документів та інших питань.",
            "faq_content_title_3": "Як проходить Отримання тендерного рішення?",
            "faq_content_text_3": "Після Вашого погодження заказу, менеджер BuyPro супроводжує поставки до моменту закриття його, вирішуючи всі питання стосовно Якості та кількості товарів та послуг, комплектності документів та інших питань.",
            "faq_content_title_4": "Як передається заявка на поставку?",
            "faq_content_text_4": "Після Вашого погодження заказу, менеджер BuyPro супроводжує поставки до моменту закриття його, вирішуючи всі питання стосовно Якості та кількості товарів та послуг, комплектності документів та інших питань.",
            "faq_content_title_5": "Як проходить Отримання тендерного рішення?",
            "faq_content_text_5": "Після Вашого погодження заказу, менеджер BuyPro супроводжує поставки до моменту закриття його, вирішуючи всі питання стосовно Якості та кількості товарів та послуг, комплектності документів та інших питань.",
            "faq_content_title_6": "Як передається заявка на поставку?",
            "faq_content_text_6": "Після Вашого погодження заказу, менеджер BuyPro супроводжує поставки до моменту закриття його, вирішуючи всі питання стосовно Якості та кількості товарів та послуг, комплектності документів та інших питань.",
            "want_remove_notification": "Ви дійсно хочите видалити повідомлення?",
            "notifications_empty": "Повідомлення відсутні",
            "order": "Замовлення",
            "description": "Опис",
            "chat": "Чат",
            "read_more": "Детальніше",
            "to_create_order": "Щоб додати нову заявку натисніть “+”",
            "bids": "Заявки",
            "check_internet": "Перевірте доступність інтернет-зв'язку.",
            "confirmed": "Підтверждено",
            "rejected": "Відхилено",
            "received": "Отримано",
            "in_transit": "У дорозі",
            "expected": "Очікується",
            "not_enough_rights_short": "Недостатньо прав",
            "perform_actions": "на виконання даних дій",
            "goods_name": "Найменування товару",
            "supplier_item": "Товар постачальника",
            "supplier_comment": "Кометар постачальника",
            "price": "Ціна",
            "quantity": "Кількість",
            "sum": "Сума",
            "note": "Примітка",
            "confirm_arrive_product": "Ви впевнені, що хочете пiдтвердити отримання товару?",
            "new_processing": "Новий. Очікує обробки",
            "choice_supplier": "Вибір постачальника",
            "requires_confirm": "Вимагає підтвердження",
            "docs": "Документи",
            "delivery_expected": "Доставка очікується",
            "confirmed": "Підтверджений",
            "delivery_success": "Доставка успішна",
            "suppliers": "Постачальники",
            "inform_picked_suppliers": "Дякуємо, що обрали постачальників. Чекайте на зворотній зв'язок від менеджера.",
            "pick_suppplier_p1": "Ви впевнені, що хочете обрати постачальника",
            "pick_suppplier_p2": "для Вашої заявки?",
            "want_confirm_receipt": "Ви впевнені, що хочете пiдтвердити отримання товару?",
            "decline_suppplier_p1": "Ви впевнені, що хочете відмовитись від послуг постачальника",
            "decline_suppplier_p2": "для Вашої заявки?",
            "warning": "Попередження",
            "product_will_delete_p1": "Товар ",
            "product_will_delete_p2": "буде видалений з заявки. Продовжити?",
            "create_application": "Створення заявки",
            "title": "Назва",
            "add_from_catalog": "Додати з каталогу",
            "delivery_address": "Адреса доставки товарів",
            "start_date": "Дата початку",
            "completion_date": "Дата завершення",
            "bidding_end_time": "Час закінчення торгів",
            "attached_files": "Вкладені файли",
            "from_catalog": "з каталогу",
            "by_name": "за назвою",
            "product_category": "Категорія товару",
            "product_subcategory": "Виберіть підкатегорію",
            "goods": "Товар",
            "choose_product": "Виберіть товар",
            "max_price": "Максимальна ціна",
            "enter_product_name": "Введіть назву для пошуку товару",
            "no_such_product": "Нажаль, такого товару не знайдено",
            "back": "Назад",
            "add": "Додати",
            "procurement_delegation": "Делегування закупок",
            "save_money": "Економія коштів",
            "process_automation": "Автоматизація процесів",
            "to_register": "До реєстрації",
            "next": "Далі",
            "send_contract_link": "Надіслати посилання на договір: ",
            "add_doc": "Додати документ",
            "send_to_email": "Надіслати по email",
            "file_will_send_p1": "Обраний файл ",
            "file_will_send_p2": " буде надіслано менеджеру.",
            "privacy_policy": "Політика конфіденційності",
            "send_contract_to_email": "Надіслати договір на Вашу email адресу ?",
            "load_audio_error": "Помилка при завантаженні аудіо",
            "order_type": "Вид замовлення",
            "purchase": "Закупівля",
            "additional_conditions": "Додаткові умови",
            "everything_correct": "Все вірно!",
            "initial_form_app": "Актуальний вигляд заявки",
            "current_form_app": "Початковий вигляд заявки",
            "error": "Помилка!",
            "please_log_in": "Будь ласка, авторизуйтесь.",
            "incorrect_failed_data": "Невірно заповнені дані",
            "all_employees_must_filled": "Необхідно заповнити всі поля для нових співробітників",
            "register": "Реєстрація",
            "auth": "Авторизація",
            "inputed_pass_lost_security": "Введений Вами пароль не задовольняє правилам безпеки.",
            "accepted_app": "Дякуємо, ми прийняли Вашу заявку. Ми повідомимо Вас по email, коли заявка буде оброблена.",
            "pass_changed": "Пароль змінено. Будь ласка, авторизуйтеся, використовуючи Ваш новий пароль",
            "create_pass_to_accout": "Створіть пароль до акаунта, який повинен містити латинські букви, інші символи та хоча б 1 цифру.",
            "pass_cant_contain_spaces": "Пароль не може містити пробіли.",
            "password": "Пароль",
            "repeat_password": "Повторіть пароль",
            "do_register": "Зареєструватися",
            "create": "Створити",
            "code_5_digit_long": "Код повинен складатися з 5 цифр.",
            "code_doesnot_match_from_email": "Введений Вами код не співпадає з кодом, відправленим на Email",
            "thx_for_register": "Дякуємо, Ви зареєструвалися. Ми повідомимо Вас по email, коли заявка буде оброблена.",
            "send_code_to_email": "Вам було надiслано код на пошту",
            "confirm": "Підтвердити",
            "email_incorrect": "Email невірний",
            "pass_must_8_chartrs_long": "Пароль має бути не меньш ніж 8 символів",
            "auth_error": "Помилка авторизації!",
            "something_went_wrong": "Щось пішло не так!",
            "for_auth_read_privacy_policy": "Для авторизації ознайомтесь, будь ласка, із політикою конфіденційності",
            "auth_google": "Через Google акаунт",
            "log_in": "Увійти",
            "not_have_user_by_data": "Не існує користувача з такими даними",
            "please_say_email": "Будь ласка, вкажіть Ваш email",
            "send_code": "Надіслати код",
            "reg_error": "Помилка регістрації!",
            "PIB": "ПІБ",
            "check_inputed_data": "Перевірте введені дані.",
            "something_went_wrong_check_data": "Щось пішло не так, перевірте введені дані",
            "audio_will_deleted": "Аудіозапис буде видалено",
            "delete_file": "Видалити файл?",
            "": "",
        },
        en: { 
            "personal_data": "Personal data",
            "contact_info": "Contact information",
            "company": "Company",
            "surname": "Surname",
            "name": "Name",
            "last_name": "Last name",
            "email": "Email",
            "phone_number": "Phone number",
            "additional_phone_number": "Additional phone number",
            "company_name": "Company name",
            "EDRPOU": "EDRPOU",
            "IBAN": "IBAN number",
            "added_max_employees": "You have added the maximum number of employees",
            "company_contacts": "Company contacts",
            "docs_delivery_address": "Delivery address of documents",
            "gods_delivery_address": "Delivery address of goods",
            "employees_company_list": "List of company employees",
            "full": "Full",
            "half": "Half",
            "will_removed_from_employee_list": "will be removed from the list of employees.",
            "continue": "Сontinue?",
            "yes": "Yes",
            "no": "No",
            "ok": "OK",
            "not_enough_rights": "Unfortunately, you do not have enough rights.",
            "of_course": "Of course",
            "employee_pib": "Name of employee",
            "employee_email": "Email employee",
            "employee_role": "The role of the employee",
            "add_employee": "Add an employee",
            "delete_employee": "Delete employee",
            "two_factor_auth": "Two-factor authentication",
            "notifications": "Notifications",
            "FAQ": "FAQ",
            "invite_users": "Invite users",
            "settings_language_title": "App Language",
            "save_changes": "Save changes",
            "want_to_quit": "Are you sure you want to quit?",
            "data_will_lost": "In case of unsaved data, they will be lost",
            "tech_error": "Technical error!",
            "profile_changes_saved": "Thanks, the changes to your profile will be saved!",
            "faq_content_title_1": "How does BuyPro conduct the tender procedure?",
            "faq_content_text_1": "After your order is approved, the BuyPro manager accompanies deliveries until it closes, resolving all issues related to the quality and quantity of goods and services, completeness of documents and other issues.",
            "faq_content_title_2": "How to submit an application for delivery?",
            "faq_content_text_2": "After your order is approved, the BuyPro manager accompanies deliveries until it closes, resolving all issues related to the quality and quantity of goods and services, completeness of documents and other issues.",
            "faq_content_title_3": "How is the receipt of the tender decision?",
            "faq_content_text_3": "After your order is approved, the BuyPro manager accompanies deliveries until it closes, resolving all issues related to the quality and quantity of goods and services, completeness of documents and other issues.",
            "faq_content_title_4": "How is a purchase order submitted?",
            "faq_content_text_4": "After your order is approved, the BuyPro manager accompanies deliveries until it closes, resolving all issues related to the quality and quantity of goods and services, completeness of documents and other issues.",
            "faq_content_title_5": "How is the receipt of the tender decision?",
            "faq_content_text_5": "After your order is approved, the BuyPro manager accompanies deliveries until it closes, resolving all issues related to the quality and quantity of goods and services, completeness of documents and other issues.",
            "faq_content_title_6": "How is a purchase order submitted?",
            "faq_content_text_6": "After your order is approved, the BuyPro manager accompanies deliveries until it closes, resolving all issues related to the quality and quantity of goods and services, completeness of documents and other issues.",
            "want_remove_notification": "Are you sure you want to delete the message?",
            "notifications_empty": "No messages",
            "order": "Order",
            "description": "Description",
            "chat": "Chat",
            "read_more": "Read more",
            "to_create_order": "To add a new application, press "+"",
            "bids": "Bids",
            "check_internet": "Check the availability of Internet connection.",
            "confirmed": "Confirmed",
            "rejected": "Rejected",
            "received": "Received",
            "in_transit": "In transit",
            "expected": "Expected",
            "not_enough_rights_short": "Not enough rights",
            "perform_actions": "to perform these actions",
            "goods_name": "Name of goods",
            "supplier_item": "Supplier's goods",
            "supplier_comment": "Supplier comment",
            "price": "Price",
            "quantity": "Guantity",
            "sum": "Sum",
            "note": "Note",
            "confirm_arrive_product": "Are you sure you want to confirm receipt of the goods?",
            "new_processing": "New. Awaiting processing",
            "choice_supplier": "Choice of supplier",
            "requires_confirm": "Requires confirmation",
            "docs": "Documents",
            "delivery_expected": "Delivery is expected",
            "confirmed": "Confirmed",
            "delivery_success": "Delivery successful",
            "suppliers": "Suppliers",
            "inform_picked_suppliers": "Thank you for choosing suppliers. Wait for feedback from the manager.",
            "pick_suppplier_p1": "Are you sure you want to select a supplier ",
            "pick_suppplier_p2": "for your application?",
            "want_confirm_receipt": "Are you sure you want to confirm receipt of the goods?",
            "decline_suppplier_p1": "Are you sure you want to opt out of the provider's services ",
            "decline_suppplier_p2": "for your application?",
            "warning": "Warning",
            "product_will_delete_p1": "The product ",
            "product_will_delete_p2": "will be removed from the application. Continue?",
            "create_application": "Creating an application",
            "title": "Name",
            "add_from_catalog": "Add from catalog",
            "delivery_address": "Delivery address of goods",
            "start_date": "Start date",
            "completion_date": "Completion date",
            "bidding_end_time": "Bidding end time",
            "attached_files": "Attached files",
            "from_catalog": "from the catalog",
            "by_name": "by name",
            "product_category": "Product category",
            "product_subcategory": "Select a subcategory",
            "goods": "Goods",
            "choose_product": "Choose a product",
            "max_price": "Max price",
            "enter_product_name": "Enter a name to search for the product",
            "no_such_product": "Unfortunately, no such product was found",
            "back": "Back",
            "add": "Add",
            "procurement_delegation": "Delegation of procurement",
            "save_money": "Save money",
            "process_automation": "Process automation",
            "to_register": "To register",
            "next": "Next",
            "send_contract_link": "Send a link to the contract: ",
            "add_doc": "Add a document",
            "send_to_email": "Send by email",
            "file_will_send_p1": "The selected file ",
            "file_will_send_p2": " will be sent to the manager.",
            "privacy_policy": "Privacy policy",
            "send_contract_to_email": "Send a contract to your email address?",
            "load_audio_error": "Error loading audio",
            "order_type": "Order type",
            "purchase": "Purchase",
            "additional_conditions": "Additional conditions",
            "everything_correct": "Everything is correct!",
            "initial_form_app": "The initial form of the application",
            "current_form_app": "The current form of the application",
            "error": "Error!",
            "please_log_in": "Please log in.",
            "incorrect_failed_data": "Incorrectly filled in data",
            "all_employees_must_filled": "All fields for new employees must be filled",
            "register": "Registration",
            "auth": "Authorization",
            "inputed_pass_lost_security": "The password you entered does not meet security policies.",
            "accepted_app": "Thank you, we have accepted your application. We will notify you by email when the application is processed.",
            "pass_changed": "Password changed. Please log in using your new password",
            "create_pass_to_accout": "Create an account password that must contain Latin letters, other characters, and at least 1 digit.",
            "pass_cant_contain_spaces": "Password cannot contain spaces.",
            "password": "Password",
            "repeat_password": "Repeat password",
            "do_register": "Register",
            "create": "Create",
            "code_5_digit_long": "The code must be 5 digits long.",
            "code_doesnot_match_from_email": "The code you entered does not match the code sent to Email",
            "thx_for_register": "Thank you for registering. We will notify you by email when the application is processed.",
            "send_code_to_email": "You have been sent a code in the email",
            "confirm": "Confirm",
            "email_incorrect": "Email is incorrect",
            "pass_must_8_chartrs_long": "Password must be at least 8 characters long",
            "auth_error": "Authorization error!",
            "something_went_wrong": "Something went wrong!",
            "for_auth_read_privacy_policy": "For authorization, please read the privacy policy",
            "auth_google": "Google Account",
            "log_in": "Log in",
            "not_have_user_by_data": "There is no user with this data",
            "please_say_email": "Please enter your email",
            "send_code": "Send code",
            "reg_error": "Registration error!",
            "PIB": "Full name",
            "check_inputed_data": "Check the entered data.",
            "something_went_wrong_check_data": "Something went wrong, check the entered data",
            "audio_will_deleted": "The audio will be deleted",
            "delete_file": "Delete file?",
            "": "",
        },
        de: { 
            "personal_data": "persönliche Daten",
            "contact_info": "Kontaktinformation",
            "company": "Unternehmen",
            "surname": "Namenszusatz",
            "name": "Name",
            "last_name": "Familienname",
            "email": "Email",
            "phone_number": "Telefonnummer",
            "additional_phone_number": "zusätzliche Telefonnummer",
            "company_name": "der Firmenname",
            "EDRPOU": "EDRPOU",
            "IBAN": "IBAN-Nummer",
            "added_max_employees": "Sie haben die maximale Anzahl an Mitarbeitern hinzugefügt",
            "company_contacts": "Unternehmenskontakte",
            "docs_delivery_address": "Lieferadresse von Dokumenten",
            "gods_delivery_address": "Lieferadresse der Ware",
            "employees_company_list": "Liste der Mitarbeiter des Unternehmens",
            "full": "Voll",
            "half": "Unvollständig",
            "will_removed_from_employee_list": "wird aus der Mitarbeiterliste gestrichen.",
            "continue": "Fortsetzen?",
            "yes": "So",
            "no": "Nain",
            "ok": "Gut",
            "not_enough_rights": "Leider haben Sie nicht genügend Rechte.",
            "of_course": "Natürlich",
            "employee_pib": "Name des Mitarbeiters",
            "employee_email": "E-Mail-Mitarbeiter",
            "employee_role": "Die Rolle des Mitarbeiters",
            "add_employee": "Fügen Sie einen Mitarbeiter hinzu",
            "delete_employee": "Mitarbeiter löschen",
            "two_factor_auth": "Zwei-Faktor-Authentifizierung",
            "notifications": "Nachricht",
            "FAQ": "FAQ",
            "invite_users": "Benutzer einladen",
            "settings_language_title": "App-Sprache",
            "save_changes": "Änderungen speichern",
            "want_to_quit": "Sind Sie sicher, dass Sie aufhören wollen?",
            "data_will_lost": "Nicht gespeicherte Daten gehen verloren",
            "tech_error": "Technischer Fehler!",
            "profile_changes_saved": "Danke, die Änderungen an Ihrem Profil werden gespeichert!",
            "faq_content_title_1": "Wie führt BuyPro das Ausschreibungsverfahren durch?",
            "faq_content_text_1": "Nachdem Ihre Bestellung genehmigt wurde, begleitet der BuyPro-Manager die Lieferungen bis zum Abschluss und löst alle Probleme im Zusammenhang mit der Qualität und Quantität der Waren und Dienstleistungen, der Vollständigkeit der Dokumente und anderen Problemen.",
            "faq_content_title_2": "Wie stelle ich einen Lieferantrag?",
            "faq_content_text_2": "Nachdem Ihre Bestellung genehmigt wurde, begleitet der BuyPro-Manager die Lieferungen bis zum Abschluss und löst alle Probleme im Zusammenhang mit der Qualität und Quantität der Waren und Dienstleistungen, der Vollständigkeit der Dokumente und anderen Problemen.",
            "faq_content_title_3": "Wie erfolgt der Eingang der Ausschreibungsentscheidung?",
            "faq_content_text_3": "Nachdem Ihre Bestellung genehmigt wurde, begleitet der BuyPro-Manager die Lieferungen bis zum Abschluss und löst alle Probleme im Zusammenhang mit der Qualität und Quantität der Waren und Dienstleistungen, der Vollständigkeit der Dokumente und anderen Problemen.",
            "faq_content_title_4": "Wie wird eine Bestellung übermittelt?",
            "faq_content_text_4": "Nachdem Ihre Bestellung genehmigt wurde, begleitet der BuyPro-Manager die Lieferungen bis zum Abschluss und löst alle Probleme im Zusammenhang mit der Qualität und Quantität der Waren und Dienstleistungen, der Vollständigkeit der Dokumente und anderen Problemen.",
            "faq_content_title_5": "Wie erfolgt der Eingang der Ausschreibungsentscheidung?",
            "faq_content_text_5": "Nachdem Ihre Bestellung genehmigt wurde, begleitet der BuyPro-Manager die Lieferungen bis zum Abschluss und löst alle Probleme im Zusammenhang mit der Qualität und Quantität der Waren und Dienstleistungen, der Vollständigkeit der Dokumente und anderen Problemen.",
            "faq_content_title_6": "Wie wird eine Bestellung übermittelt?",
            "faq_content_text_6": "Nachdem Ihre Bestellung genehmigt wurde, begleitet der BuyPro-Manager die Lieferungen bis zum Abschluss und löst alle Probleme im Zusammenhang mit der Qualität und Quantität der Waren und Dienstleistungen, der Vollständigkeit der Dokumente und anderen Problemen.",
            "want_remove_notification": "Möchten Sie die Nachricht wirklich löschen?",
            "notifications_empty": "Keine Nachrichten",
            "order": "Befehl",
            "description": "Beschreibung",
            "chat": "Plaudern",
            "read_more": "Weiterlesen",
            "to_create_order": "Um eine neue Anwendung hinzuzufügen, drücken Sie "+"",
            "bids": "Anfragen",
            "check_internet": "Überprüfen Sie die Verfügbarkeit der Internetverbindung.",
            "confirmed": "Bestätigt",
            "rejected": "Hat abgelehnt",
            "received": "Empfangen",
            "in_transit": "Unterwegs",
            "expected": "Erwartet",
            "not_enough_rights_short": "Nicht genug Rechte",
            "perform_actions": "Um diese Aktionen auszuführen",
            "goods_name": "Artikelbezeichnung",
            "supplier_item": "Waren des Lieferanten",
            "supplier_comment": "Kommentar des Lieferanten",
            "price": "Preis",
            "quantity": "Anzahl",
            "sum": "Summe",
            "note": "Notiz",
            "confirm_arrive_product": "Möchten Sie den Wareneingang wirklich bestätigen?",
            "new_processing": "Neu. Warten auf Bearbeitung",
            "choice_supplier": "Wahl des Lieferanten",
            "requires_confirm": "Bestätigung erforderlich",
            "docs": "Unterlagen",
            "delivery_expected": "Lieferung wird erwartet",
            "confirmed": "Bestätigt",
            "delivery_success": "Lieferung erfolgreich",
            "suppliers": "Lieferanten",
            "inform_picked_suppliers": "Vielen Dank, dass Sie sich für Lieferanten entschieden haben. Warten Sie auf das Feedback des Managers.",
            "pick_suppplier_p1": "Sind Sie sicher, dass Sie einen Lieferanten ",
            "pick_suppplier_p2": "für Ihre Anwendung auswählen möchten?",
            "want_confirm_receipt": "Möchten Sie den Wareneingang wirklich bestätigen?",
            "decline_suppplier_p1": "Möchten Sie die Dienste des Anbieters ",
            "decline_suppplier_p2": "für Ihre Anwendung wirklich deaktivieren?",
            "warning": "Warnung",
            "product_will_delete_p1": "Das Produkt ",
            "product_will_delete_p2": "wird aus der Anwendung entfernt. Fortsetzen?",
            "create_application": "Erstellen einer Anwendung",
            "title": "Name",
            "add_from_catalog": "Aus Katalog hinzufügen",
            "delivery_address": "Lieferadresse der Ware",
            "start_date": "Startdatum",
            "completion_date": "Fertigstellungstermin",
            "bidding_end_time": "Ende der Gebotsabgabe",
            "attached_files": "Beigefügte Anhänge",
            "from_catalog": "aus dem Katalog",
            "by_name": "namentlich",
            "product_category": "Produktkategorie",
            "product_subcategory": "Wähle eine Unterkategorie",
            "goods": "Waren",
            "choose_product": "Wählen Sie ein Produkt",
            "max_price": "Höchstpreis",
            "enter_product_name": "Geben Sie einen Namen ein, um nach dem Produkt zu suchen",
            "no_such_product": "Leider wurde kein solches Produkt gefunden",
            "back": "Zurück",
            "add": "Hinzufügen",
            "procurement_delegation": "Delegation der Beschaffung",
            "save_money": "Geld sparen",
            "process_automation": "Prozessautomatisierung",
            "to_register": "Registrierungsschlüssel",
            "next": "Weiter",
            "send_contract_link": "Senden Sie einen Link zum Vertrag: ",
            "add_doc": "Fügen Sie ein Dokument hinzu",
            "send_to_email": "Per E-Mail gesendet",
            "file_will_send_p1": "Die ausgewählte Datei ",
            "file_will_send_p2": " wird an den Manager gesendet.",
            "privacy_policy": "Datenschutz-Bestimmungen",
            "send_contract_to_email": "Einen Vertrag an Ihre E-Mail-Adresse senden?",
            "load_audio_error": "Fehler beim Laden von Audio",
            "order_type": "Auftragsart",
            "purchase": "Kaufen",
            "additional_conditions": "Zusätzliche Bedingungen",
            "everything_correct": "Alles ist richtig!",
            "initial_form_app": "Das ursprüngliche Antragsformular",
            "current_form_app": "Das aktuelle Antragsformular",
            "error": "Fehler!",
            "please_log_in": "Bitte loggen Sie sich ein.",
            "incorrect_failed_data": "Falsch ausgefüllte Daten",
            "all_employees_must_filled": "Alle Felder für neue Mitarbeiter müssen ausgefüllt werden",
            "register": "Anmeldung",
            "auth": "Genehmigung",
            "inputed_pass_lost_security": "Das eingegebene Passwort entspricht nicht den Sicherheitsrichtlinien.",
            "accepted_app": "Vielen Dank, wir haben Ihre Bewerbung angenommen. Wir benachrichtigen Sie per E-Mail, wenn der Antrag bearbeitet wird.",
            "pass_changed": "Passwort geändert. Bitte melden Sie sich mit Ihrem neuen Passwort an",
            "create_pass_to_accout": "Erstellen Sie ein Kontopasswort, das lateinische Buchstaben, andere Zeichen und mindestens eine Ziffer enthalten muss.",
            "pass_cant_contain_spaces": "Kennwort darf keine Leerzeichen enthalten.",
            "password": "Passwort",
            "repeat_password": "Passwort wiederholen",
            "do_register": "Registrieren",
            "create": "Erstellen",
            "code_5_digit_long": "Der Code muss 5 Ziffern lang sein.",
            "code_doesnot_match_from_email": "Der eingegebene Code stimmt nicht mit dem an E-Mail gesendeten Code überein",
            "thx_for_register": "Danke für die Registrierung. Wir benachrichtigen Sie per E-Mail, wenn der Antrag bearbeitet wird.",
            "send_code_to_email": "Sie haben einen Code per Post erhalten",
            "confirm": "Bestätigen Sie",
            "email_incorrect": "E-Mail ist falsch",
            "pass_must_8_chartrs_long": "Das Passwort muss mindestens 8 Zeichen lang sein",
            "auth_error": "Autorisierungsfehler!",
            "something_went_wrong": "Etwas ist schief gelaufen!",
            "for_auth_read_privacy_policy": "Zur Autorisierung lesen Sie bitte die Datenschutzerklärung",
            "auth_google": "Über ein Google-Konto",
            "log_in": "Einloggen",
            "not_have_user_by_data": "Es gibt keinen Benutzer mit diesen Informationen",
            "please_say_email": "Bitte geben Sie ihre E-Mail-Adresse ein",
            "send_code": "Code senden",
            "reg_error": "Registrierungsfehler!",
            "PIB": "FIO",
            "check_inputed_data": "Überprüfen Sie die eingegebenen Daten.",
            "something_went_wrong_check_data": "Etwas ist schief gelaufen, überprüfen Sie die eingegebenen Daten",
            "audio_will_deleted": "Der Ton wird gelöscht",
            "delete_file": "Datei löschen?",
            "": "",
        },
};

// Set the locale once at the beginning of your app.
// console.log("locale: " + i18n.translations);
// i18n.locale = Localization.locale;
i18n.locale = 'en';
// i18n.defaultLocale = i18n.translations[0];
// When a value is missing from a language it'll fallback to another language with the key present.
i18n.fallbacks = true;

// i18n.localize('uk');
// i18n.
// i18n.locale = i18n.locales[0];

export default i18n;