import * as Localization from 'expo-localization';
import i18n from 'i18n-js';

i18n.translations = {
        uk: { 
            welcome: 'Привiт!',
            "personal_data": "Особисті дані",
            "contact_info": "Контактна інформація",
            "company": "Компанія",
            "surname": "По батькові",
            "name": "Ім’я",
            "last_name": "Прізвище",
            "email": "Email",
            "phone_number": "Номер телефону",
            "additional_phone_number": "Додатковий номер телефону",
            "company_name": "Назва компанії",
            "EDRPOU": "ЄДРПОУ",
            "IBAN": "IBAN номер",
            "added_max_employees": "Ви додали максимальну кількість співробітників",
            "company_contacts": "Контакти компанії",
            "docs_delivery_address": "Адреса доставки документів",
            "gods_delivery_address": "Адреса доставки товарів",
            "employees_company_list": "Список співробітників компанії",
            "full": "Повна",
            "half": "Неповна",
            "will_removed_from_employee_list": "буде видалений із списка співробітників.",
            "continue": "Продовжити?",
            "yes": "Так",
            "no": "Ні",
            "ok": "OK",
            "not_enough_rights": "На жаль у Вас недостатньо прав.",
            "of_course": "Зрозуміло",
            "employee_pib": "ПІБ співробітника",
            "employee_email": "Email співробітника",
            "employee_role": "Роль співробітника",
            "add_employee": "Додати співробітника",
            "delete_employee": "Видалити співробітника",
            "two_factor_auth": "Двофакторна автентифікація",
            "notifications": "Повідомлення",
            "FAQ": "FAQ",
            "invite_users": "Запрошення користувачів",
            "settings_language_title": "Мова додатку",
            "save_changes": "Зберегти зміни",
            "want_to_quit": "Ви впевнені, що хочете вийти?",
            "data_will_lost": "У разі незбережених даних вони будуть втрачені",
            "tech_error": "Технічна помилка!",
            "profile_changes_saved": "Дякуємо, зміни у Вашому профілі будут збережені!",
            "faq_content_title_1": "Як BuyPro проводить тендерну процедуру?",
            "faq_content_text_1": "Після Вашого погодження заказу, менеджер BuyPro супроводжує поставки до моменту закриття його, вирішуючи всі питання стосовно Якості та кількості товарів та послуг, комплектності документів та інших питань.",
            "faq_content_title_2": "Як передають  заяву на поставку?",
            "faq_content_text_2": "Після Вашого погодження заказу, менеджер BuyPro супроводжує поставки до моменту закриття його, вирішуючи всі питання стосовно Якості та кількості товарів та послуг, комплектності документів та інших питань.",
            "faq_content_title_3": "Як проходить Отримання тендерного рішення?",
            "faq_content_text_3": "Після Вашого погодження заказу, менеджер BuyPro супроводжує поставки до моменту закриття його, вирішуючи всі питання стосовно Якості та кількості товарів та послуг, комплектності документів та інших питань.",
            "faq_content_title_4": "Як передається заявка на поставку?",
            "faq_content_text_4": "Після Вашого погодження заказу, менеджер BuyPro супроводжує поставки до моменту закриття його, вирішуючи всі питання стосовно Якості та кількості товарів та послуг, комплектності документів та інших питань.",
            "faq_content_title_5": "Як проходить Отримання тендерного рішення?",
            "faq_content_text_5": "Після Вашого погодження заказу, менеджер BuyPro супроводжує поставки до моменту закриття його, вирішуючи всі питання стосовно Якості та кількості товарів та послуг, комплектності документів та інших питань.",
            "faq_content_title_6": "Як передається заявка на поставку?",
            "faq_content_text_6": "Після Вашого погодження заказу, менеджер BuyPro супроводжує поставки до моменту закриття його, вирішуючи всі питання стосовно Якості та кількості товарів та послуг, комплектності документів та інших питань.",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
        },
        en: { 
            welcome: 'Hi',
            "personal_data": "Personal data",
            "contact_info": "Contact information",
            "company": "Company",
            "surname": "Surname",
            "name": "Name",
            "last_name": "Last name",
            "email": "Email",
            "phone_number": "Phone number",
            "additional_phone_number": "Additional phone number",
            "company_name": "Company name",
            "EDRPOU": "EDRPOU",
            "IBAN": "IBAN number",
            "added_max_employees": "You have added the maximum number of employees",
            "company_contacts": "Company contacts",
            "docs_delivery_address": "Delivery address of documents",
            "gods_delivery_address": "Delivery address of goods",
            "employees_company_list": "List of company employees",
            "full": "Full",
            "half": "Half",
            "will_removed_from_employee_list": "will be removed from the list of employees.",
            "continue": "Сontinue?",
            "yes": "Yes",
            "no": "No",
            "ok": "OK",
            "not_enough_rights": "Unfortunately, you do not have enough rights.",
            "of_course": "Of course",
            "employee_pib": "Name of employee",
            "employee_email": "Email employee",
            "employee_role": "The role of the employee",
            "add_employee": "Add an employee",
            "delete_employee": "Delete employee",
            "two_factor_auth": "Two-factor authentication",
            "notifications": "Notifications",
            "FAQ": "FAQ",
            "invite_users": "Invite users",
            "settings_language_title": "App Language",
            "save_changes": "Save changes",
            "want_to_quit": "Are you sure you want to quit?",
            "data_will_lost": "In case of unsaved data, they will be lost",
            "tech_error": "Technical error!",
            "profile_changes_saved": "Thanks, the changes to your profile will be saved!",
            "faq_content_title_1": "How does BuyPro conduct the tender procedure?",
            "faq_content_text_1": "After your order is approved, the BuyPro manager accompanies deliveries until it closes, resolving all issues related to the quality and quantity of goods and services, completeness of documents and other issues.",
            "faq_content_title_2": "How to submit an application for delivery?",
            "faq_content_text_2": "After your order is approved, the BuyPro manager accompanies deliveries until it closes, resolving all issues related to the quality and quantity of goods and services, completeness of documents and other issues.",
            "faq_content_title_3": "How is the receipt of the tender decision?",
            "faq_content_text_3": "After your order is approved, the BuyPro manager accompanies deliveries until it closes, resolving all issues related to the quality and quantity of goods and services, completeness of documents and other issues.",
            "faq_content_title_4": "How is a purchase order submitted?",
            "faq_content_text_4": "After your order is approved, the BuyPro manager accompanies deliveries until it closes, resolving all issues related to the quality and quantity of goods and services, completeness of documents and other issues.",
            "faq_content_title_5": "How is the receipt of the tender decision?",
            "faq_content_text_5": "After your order is approved, the BuyPro manager accompanies deliveries until it closes, resolving all issues related to the quality and quantity of goods and services, completeness of documents and other issues.",
            "faq_content_title_6": "How is a purchase order submitted?",
            "faq_content_text_6": "After your order is approved, the BuyPro manager accompanies deliveries until it closes, resolving all issues related to the quality and quantity of goods and services, completeness of documents and other issues.",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
        },
        de: { 
            welcome: 'Hallo!',
            "personal_data": "persönliche Daten",
            "contact_info": "Kontaktinformation",
            "company": "Unternehmen",
            "surname": "Namenszusatz",
            "name": "Name",
            "last_name": "Familienname",
            "email": "Email",
            "phone_number": "Telefonnummer",
            "additional_phone_number": "zusätzliche Telefonnummer",
            "company_name": "der Firmenname",
            "EDRPOU": "EDRPOU",
            "IBAN": "IBAN-Nummer",
            "added_max_employees": "Sie haben die maximale Anzahl an Mitarbeitern hinzugefügt",
            "company_contacts": "Unternehmenskontakte",
            "docs_delivery_address": "Lieferadresse von Dokumenten",
            "gods_delivery_address": "Lieferadresse der Ware",
            "employees_company_list": "Liste der Mitarbeiter des Unternehmens",
            "full": "Voll",
            "half": "Unvollständig",
            "will_removed_from_employee_list": "wird aus der Mitarbeiterliste gestrichen.",
            "continue": "Fortsetzen?",
            "yes": "So",
            "no": "Nain",
            "ok": "Gut",
            "not_enough_rights": "Leider haben Sie nicht genügend Rechte.",
            "of_course": "Natürlich",
            "employee_pib": "Name des Mitarbeiters",
            "employee_email": "E-Mail-Mitarbeiter",
            "employee_role": "Die Rolle des Mitarbeiters",
            "add_employee": "Fügen Sie einen Mitarbeiter hinzu",
            "delete_employee": "Mitarbeiter löschen",
            "two_factor_auth": "Zwei-Faktor-Authentifizierung",
            "notifications": "Nachricht",
            "FAQ": "FAQ",
            "invite_users": "Benutzer einladen",
            "settings_language_title": "App-Sprache",
            "save_changes": "Änderungen speichern",
            "want_to_quit": "Sind Sie sicher, dass Sie aufhören wollen?",
            "data_will_lost": "Nicht gespeicherte Daten gehen verloren",
            "tech_error": "Technischer Fehler!",
            "profile_changes_saved": "Danke, die Änderungen an Ihrem Profil werden gespeichert!",
            "faq_content_title_1": "Wie führt BuyPro das Ausschreibungsverfahren durch?",
            "faq_content_text_1": "Nachdem Ihre Bestellung genehmigt wurde, begleitet der BuyPro-Manager die Lieferungen bis zum Abschluss und löst alle Probleme im Zusammenhang mit der Qualität und Quantität der Waren und Dienstleistungen, der Vollständigkeit der Dokumente und anderen Problemen.",
            "faq_content_title_2": "Wie stelle ich einen Lieferantrag?",
            "faq_content_text_2": "Nachdem Ihre Bestellung genehmigt wurde, begleitet der BuyPro-Manager die Lieferungen bis zum Abschluss und löst alle Probleme im Zusammenhang mit der Qualität und Quantität der Waren und Dienstleistungen, der Vollständigkeit der Dokumente und anderen Problemen.",
            "faq_content_title_3": "Wie erfolgt der Eingang der Ausschreibungsentscheidung?",
            "faq_content_text_3": "Nachdem Ihre Bestellung genehmigt wurde, begleitet der BuyPro-Manager die Lieferungen bis zum Abschluss und löst alle Probleme im Zusammenhang mit der Qualität und Quantität der Waren und Dienstleistungen, der Vollständigkeit der Dokumente und anderen Problemen.",
            "faq_content_title_4": "Wie wird eine Bestellung übermittelt?",
            "faq_content_text_4": "Nachdem Ihre Bestellung genehmigt wurde, begleitet der BuyPro-Manager die Lieferungen bis zum Abschluss und löst alle Probleme im Zusammenhang mit der Qualität und Quantität der Waren und Dienstleistungen, der Vollständigkeit der Dokumente und anderen Problemen.",
            "faq_content_title_5": "Wie erfolgt der Eingang der Ausschreibungsentscheidung?",
            "faq_content_text_5": "Nachdem Ihre Bestellung genehmigt wurde, begleitet der BuyPro-Manager die Lieferungen bis zum Abschluss und löst alle Probleme im Zusammenhang mit der Qualität und Quantität der Waren und Dienstleistungen, der Vollständigkeit der Dokumente und anderen Problemen.",
            "faq_content_title_6": "Wie wird eine Bestellung übermittelt?",
            "faq_content_text_6": "Nachdem Ihre Bestellung genehmigt wurde, begleitet der BuyPro-Manager die Lieferungen bis zum Abschluss und löst alle Probleme im Zusammenhang mit der Qualität und Quantität der Waren und Dienstleistungen, der Vollständigkeit der Dokumente und anderen Problemen.",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
        },
};

// Set the locale once at the beginning of your app.
// console.log("locale: " + i18n.translations);
// i18n.locale = Localization.locale;
i18n.locale = 'en';
// i18n.defaultLocale = i18n.translations[0];
// When a value is missing from a language it'll fallback to another language with the key present.
i18n.fallbacks = true;

// i18n.localize('uk');
// i18n.
// i18n.locale = i18n.locales[0];

export default i18n;